# Generated by Django 5.0.1 on 2024-02-02 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_phonecharge_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecharge",
            name="tracking_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
