# Generated by Django 5.0.1 on 2024-02-02 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_rename_result_transaction_status"),
        ("user", "0003_phonecharge_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonecharge",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charge",
                to="financial.transaction",
            ),
        ),
    ]
