# Generated by Django 5.0.1 on 2024-02-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_phonecharge_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phonecharge",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="phonecharge",
            name="status",
        ),
        migrations.RemoveField(
            model_name="phonecharge",
            name="tracking_code",
        ),
    ]
