# Generated by Django 5.0.1 on 2024-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_phonecharge_tracking_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecharge",
            name="amount",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
